const SHOP_DATA = {
  yolkfolk: {
    id: 1,
    title: "Yolk Folk",
    routeName: "yolkfolk",
    items: [
      {
        id: 1,
        name: "Sticker Sheet",
        catagory: "yolkfolk",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 25,
      },
      {
        id: 2,
        name: "Pins",
        catagory: "yolkfolk",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 10,
      },
      {
        id: 3,
        name: "Print",
        catagory: "yolkfolk",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 10,
      },
      {
        id: 4,
        name: "The Full Collection",
        catagory: "yolkfolk",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 45,
      },
    ],
  },
  cafecats: {
    id: 2,
    title: "Cafè Cats",
    routeName: "cafecats",
    items: [
      {
        id: 1,
        name: "Mug",
        catagory: "cafecats",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 25,
      },
      {
        id: 2,
        name: "Sticker Sheet",
        catagory: "cafecats",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 7,
      },
      {
        id: 3,
        name: "Pins",
        catagory: "cafecats",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 10,
      },
      {
        id: 4,
        name: "Print",
        catagory: "cafecats",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 10,
      },
      {
        id: 5,
        name: "The Full Collection",
        catagory: "cafecats",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 65,
      },
    ],
  },
  coneappetit: {
    id: 3,
    title: "Cone Appètit",
    routeName: "coneappetit",
    items: [
      {
        id: 1,
        name: "Sticker Sheet",
        catagory: "coneappetit",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 25,
      },
      {
        id: 2,
        name: "Pins",
        catagory: "coneappetit",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 10,
      },
      {
        id: 3,
        name: "Print",
        catagory: "coneappetit",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 10,
      },
      {
        id: 4,
        name: "The Full Collection",
        catagory: "coneappetit",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 45,
      },
    ],
  },
  snailglobes: {
    id: 4,
    title: "Snail Globes",
    routeName: "snailglobes",
    items: [
      {
        id: 1,
        name: "Sticker Sheet",
        catagory: "snailglobes",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 25,
      },
      {
        id: 2,
        name: "Pins",
        catagory: "snailglobes",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 10,
      },
      {
        id: 3,
        name: "Print",
        catagory: "snailglobes",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 10,
      },
      {
        id: 4,
        name: "The Full Collection",
        catagory: "snailglobes",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 45,
      },
    ],
  },
  tchotchkes: {
    id: 5,
    title: "Tchotchkes",
    routeName: "tchotchkes",
    items: [
      {
        id: 5,
        name: "Sticker Sheet",
        imageUrl: "https://via.placeholder.com/265/350.png",
        price: 10,
      },
    ],
  },
};
export default SHOP_DATA;
