import React from "react";
import selectPOS from "../../components/select-pos/selectPOS.component";
const PROMPT_DATA = {
  blanks: [
    `${selectPOS("noun")} in the library`,
    `${selectPOS("noun")} in the forest`,
    `${selectPOS("noun")} in the attic`,
    `${selectPOS("noun")} in the fog`,
    `${selectPOS("noun")} in the water`,
    `${selectPOS("anthro")} as a princess`,
    `${selectPOS("anthro")} as a prince`,
    `${selectPOS("anthro")} as a nonbinary heir to the throne`,
    `Inside ${selectPOS("inNoun")}`,
    `${selectPOS("noun")} inside ${selectPOS("inNoun")}`,
    `${selectPOS("witch")} witch`,
  ],
  westSigns: [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
  ],
  chineseSigns: [
    "Rat",
    "Ox",
    "Tiger",
    "Rabit",
    "Dragon",
    "Snake",
    "Horse",
    "Sheep",
    "Monkey",
    "Rooster",
    "Dog",
    "Pig",
  ],
  people: [],
  places: [],
  things: [],
  ideas: [],
  activities: [],
  food: [],
  drinks: [],
  noun: ["house"], //needs function to select from noun types
  anthro: ["rat"],
  inNouns: ["box"],
  witch: ["cute"],
  verbs: [],
  adjectives: [],
};
export default PROMPT_DATA;
